- name: Install user component 
  hosts: user
  become: yes

  tasks: 

  - name: NodeJS repos. Vendor is providing a script to setup the repos setup NPM resources
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: install nodejs
    ansible.builtin.yum: 
      name: nodejs
      state: installed 

  - name: check roboshop user exist or not   #here we are checking either the robosho user exist or not 
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true 

  - when: out.rc != 0 
    name: create user roboshop 
    become: yes
    ansible.builtin.user: 
      name: roboshop  

  - name: create /app directory exist or not 
    ansible.builtin.stat:
      path: /app
    register: directory


  - name: print the directory stats
    ansible.builtin.debug: 
      msg: "output: {{directory}}"

  - when: directory.stat.exists == false
    name: create /app directory 
    ansible.builtin.file: 
      path: /app
      state: directory


  - name: Download Application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
  

  - name: Extract user artifact 
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies npm
    ansible.builtin.command: npm install
    args: 
      chdir: /app

  - name: Copy user services
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: demon reload 
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Copy mongo repo file to yum.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb
    ansible.builtin.yum: 
      name: mongodb-org-shell
      state: installed

  - name: loading schema user data 
    ansible.builtin.command: mongo --host mongodb.nishalkdevops.online </app/schema/user.js

  - name: restart user
    ansible.builtin.service: 
      name: user
      state: restarted
      enabled: true 