- name: Install web component
  hosts: web
  become: yes

  tasks: 
  - name: To install Nginx
    ansible.builtin.yum: 
      name: nginx
      state: installed

  - name: To start and enable nginx
    ansible.builtin.service: 
      name: nginx
      state: started
      enabled: yes